In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back python int
scalar.item()

7

In [6]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim #no.of square brackets

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX = torch.tensor([[7,8],
 [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

###random Tensor
[link text](https://)
Random tensors are imp beacause the way many neural netwuorks  is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [21]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.5551, 0.4537, 0.2988, 0.8002],
         [0.9291, 0.8567, 0.5611, 0.6858],
         [0.1851, 0.8014, 0.2001, 0.5650]]])

In [22]:
random_tensor.ndim

3

In [23]:
#create a random_tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # red green blue
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
###Zeros and Ones




```
# This is formatted as code
```



In [25]:
#create  a tensor  of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_tensor.dtype

torch.float32

In [32]:
###create a range of tensors and tensors like

..

In [34]:
#use torch.range()
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [35]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

```
# This is formatted as code
```Note :Tensor is one of the 3 big errors you will run into pytorch & deep learning
1.Tensors are not right datatype
2.tensors  mot right shape
3.tensors not on the right device



In [42]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor *float_32_tensor

tensor([ 9., 36., 81.])

In [47]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [48]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])