In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back python int
scalar.item()

7

In [6]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim #no.of square brackets

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],
 [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

###random Tensor
[link text](https://)
Random tensors are imp beacause the way many neural netwuorks  is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [18]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.9643, 0.2582, 0.4701, 0.1315],
         [0.7206, 0.3681, 0.1345, 0.9282],
         [0.2061, 0.2661, 0.9789, 0.5115]]])

In [19]:
random_tensor.ndim

3

In [20]:
#create a random_tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # red green blue
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
###Zeros and Ones




```
# This is formatted as code
```



In [22]:
#create  a tensor  of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

In [27]:
###create a range of tensors and tensors like

..

In [28]:
#use torch.range()
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

```
# This is formatted as code
```Note :Tensor is one of the 3 big errors you will run into pytorch & deep learning
1.Tensors are not right datatype
2.tensors  mot right shape
3.tensors not on the right device



In [30]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor *float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
###getting information from tensors

#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0056, 0.5834, 0.3750, 0.8207],
        [0.0586, 0.9827, 0.2167, 0.0928],
        [0.2661, 0.3005, 0.0272, 0.9120]])

In [37]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [38]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.size}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.0056, 0.5834, 0.3750, 0.8207],
        [0.0586, 0.9827, 0.2167, 0.0928],
        [0.2661, 0.3005, 0.0272, 0.9120]])
Datatype of tensor:torch.float32
shape of tensor:<built-in method size of Tensor object at 0x7b2b99779620>
device tensor is on:cpu


In [112]:
###manipulating tensor (tensor operations)
#Tensor operation includes:
#Addition
#subtraction
#Multiplication
#Division
#Matrix multiplication


In [40]:
#create a tensor
tensor= torch.tensor([1,2,3])
tensor+100


tensor([101, 102, 103])

In [43]:
tensor*10

tensor([10, 20, 30])

In [44]:
#try out pytorch inbulit function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [42]:
###marix multiplication
1. element wise
matix multiplication dot  product

SyntaxError: invalid syntax (<ipython-input-42-f16304514bfe>, line 2)

In [45]:
#element wise multiplication
print(tensor ,"*", tensor)
print(f"Equals:{tensor *tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [46]:
#mATRIX MULTIPLUCATION
torch.matmul(tensor,tensor)

tensor(14)

In [47]:
#maTRIx multiplication by hand
1*1 + 2*2 +3*3

14

In [48]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.86 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

In [50]:
#one of thee most common errors in deep learning: shape errors
#shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
 [3,4],
  [5,6]])
tensor_B = torch.tensor([[1,2],
 [3,4],
  [5,6]])


In [58]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
torch.min(x) ,x.min()

(tensor(0), tensor(0))

In [60]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [61]:
#find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [55]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
##finding the positional min and max

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
#find the pisition in tensor
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

In [69]:
#reshaping,stacking,squeezing, and unsqueezing tensors
import torch
x =torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

In [71]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
z[:0]=5
z,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

In [75]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x_reshaped.shape

torch.Size([1, 9])

In [77]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
x_reshaped.squeeze().shape

torch.Size([9])

In [79]:
#torch .unsquueeze- adds a single dimension to a target tensor at a specific dim

In [80]:
print(f"previous target:{x_squeezed}")
print(f"previous target:{x_squeezed.shape}")

NameError: name 'x_squeezed' is not defined

In [81]:
#torch.permute - rearranges  the dimensions of  a target tensor in a specified order
x_original=torch.rand(size=(2,24,3)) #h,width,color_channel
x_permuted=x_original.permute(2,0,1)
print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

previous shape:torch.Size([2, 24, 3])
new shape:torch.Size([3, 2, 24])


In [82]:

x_original[0,0:0]=728216

In [83]:
#indexing with Pytorch is similar to indexing with numpy
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
#let's index on the middle bracket
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [90]:
#lets index on the most inner bracket
x[0][2][2]

tensor(9)

In [91]:
#you can also useeeee ":" to select "all " of a  target dimension
x[:,0]

tensor([[1, 2, 3]])

In [92]:
# get all values of 0th and 1st dimension but only index 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [93]:
x[:,1,1]

tensor([5])

In [94]:
x[0,0,:]

tensor([1, 2, 3])

In [95]:
#pytorch tensors and numpy
#Data in numpy ,want in pytorch tensor ->torch.from_numpy(ndarray)

In [97]:
#Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #when converting from numpy ->pytorch  reflects numpy's default datatype of float64unless specified others
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
array.dtype

dtype('float64')

In [99]:
tensor.dtype

torch.float64

In [100]:
#chane the value of array,what will thsi to do to'tensor'?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
#tensor  to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), <function Tensor.numpy>)

In [107]:
#change the tensor, what happens to 'numpy_ tensor'?
tensor = tensor+1
tensor,numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]), <function Tensor.numpy>)

In [108]:
##Reproducilibity (trying to take random out of random)

In [111]:
##To reduce the randomness in N.N and pytorch comes the concept of a random seed
#essentiallay  what the random seed does is "flavour" the randomness

In [114]:
import torch

#creating two random tensors
random_tensor_A =torch.rand(3,4)
random_tensor_B= torch.rand(3,4)
print(random_tensor_A )
print(random_tensor_B )
print(random_tensor_A == random_tensor_B)

tensor([[0.0249, 0.8424, 0.1927, 0.4055],
        [0.9056, 0.9698, 0.8924, 0.3540],
        [0.6414, 0.9640, 0.7079, 0.5598]])
tensor([[0.8365, 0.1087, 0.8523, 0.8049],
        [0.3657, 0.2461, 0.1224, 0.6314],
        [0.1687, 0.3893, 0.5149, 0.1376]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [117]:
#lets make some random but reproducible tensors
import torch

#set the randomseed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C= torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D =torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [118]:
##running tensors and pytorchh on the gpus